### ISSUE TITLE
Dojo magic reconnection disturbs pwntools.ssh

### ISSUE THREAD

**Issue by ysf** [pwncollege/dojo#100]
Hey there,

because of Dojos "Connecting" and  messages and automagic reconnect on exit with a failure code when a ssh command is send, the pwntools either don't work, or enter some infinite loops when trying to use pwntools ssh tubes with pwn.college.

https://github.com/pwncollege/dojo/blob/64b417f9acbaad7cd43f6519c34f1efd69fd2906/ssh/enter.py#L55
https://github.com/pwncollege/dojo/blob/64b417f9acbaad7cd43f6519c34f1efd69fd2906/ssh/enter.py#L75-L79

**Comment by ConnorNelson** [comment]
Hey!

I would be happy to push all "extra" output to stderr instead of stdout if that helps. 

However, I value auto-reconnecting above pwntools ssh functionality.

That being said, there is probably something we can do about this. For example, if we haven't allocated a pty (`SSH_TTY`), we can not loop. We will have to investigate if this would resolve this, otherwise, maybe an environment variable to not auto-reconnect would make things better.
