### ISSUE TITLE
ldd incorrectly lists libraries from nix store

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#471]
This is particularly relevant for heap related challenges where libc version is relevant.

```
hacker@practice~dynamic-allocator-misuse~level7-0:~$ /usr/bin/ldd /challenge/babyheap_level7.0
	linux-vdso.so.1 (0x00007fff9e3d6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6955e96000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6956095000)
hacker@practice~dynamic-allocator-misuse~level7-0:~$
```

```
hacker@practice~dynamic-allocator-misuse~level7-0:~$ ldd /challenge/babyheap_level7.0
	linux-vdso.so.1 (0x00007ffdf55c3000)
	libc.so.6 => /nix/store/dbcw19dshdwnxdv5q2g6wldj6syyvq7l-glibc-2.39-52/lib/libc.so.6 (0x00007f16b859c000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/dbcw19dshdwnxdv5q2g6wldj6syyvq7l-glibc-2.39-52/lib64/ld-linux-x86-64.so.2 (0x00007f16b878b000)
```

**Comment by zardus** [comment]
That's really weird that it would do this...

I wonder if, for pwnables, we should have `/usr/bin/ldd` be the default in the path?

**Comment by Scoder12** [comment]
It makes sense because ldd is basically asking the dynamic interpreter how it would resolve the requests the binary makes. The dynamic interpreter will even act as `ldd` for you if you set `LD_TRACE_LOADED_OBJECTS` when running the binary. 

If you ask the ubuntu interpreter for libc, it will return the ubuntu libc that it is programmed to find. If you ask the nix interpreter for libc, it will return the nix libc that it knows about. 

One solution could be making `ldd` a wrapper script that checks the interpreter programmed in to the binary, which can be found on the last line of that ldd output. In this case, it's `/lib64/ld-linux-x86-64.so.2` so we should shell out to `/usr/bin/ldd`. If it was a /nix/store path we should shell out to `/run/current-system/sw/bin/ldd`. A bit more complicated but it would ensure ldd works properly on both nix and non-nix binaries.
