### ISSUE TITLE
Bug: Column size for ssh public keys no longer big enough for some SHA 256 public keys.

### ISSUE THREAD

**Issue by spicydll** [pwncollege/dojo#541]
In the current main branch, SSH keys that have public keys longer than 512 characters, such as many SHA 256 public keys, cannot be submitted or stored in the database.

This bug was introduced as a result of [this commit 3 months ago](https://github.com/pwncollege/dojo/blame/0e100edae38ef5fea57f91b75031d7a73aa6c5db/dojo_plugin/models/__init__.py#L690). The column type was formally `db.text`, which maps to [MySQL's `TEXT` datatype](https://stackoverflow.com/questions/47644739/what-column-type-does-sqlalchemy-use-for-text-on-mysql). This supports [strings up to 64 KB](https://stackoverflow.com/a/66274965). This is definitely overkill, so it makes sense to not use this type.

However, the column type was changed to `db.String(512)` in [`dojo_plugin/models/__init__.py`](https://github.com/pwncollege/dojo/blob/0e100edae38ef5fea57f91b75031d7a73aa6c5db/dojo_plugin/models/__init__.py#L690), which fixes the size to 512 bytes. This is unfortunately not enough for several standard key sizes such as SHA 256 with 4096 bits. The public key I use on the prod site, for example, is 553 bytes in length. Another key I just generated is 725 bytes in length.

I think a length that would suffice for these keys would be 1024, or 2048 to be safe.

In addition, when this failure occurs, the api fails silently with a 500 server error. There should be error handling added to inform the user that their key is too long.

This bug doesn't appear to be affecting the main prod site right now, as I was just able to add an oversized SSH public key. However, the current version you get from standing up this repo does exhibit the bug.

**Comment by spicydll** [comment]
I will submit a PR for the error handling. I will wait for more discussion to change the column size

**Comment by ConnorNelson** [comment]
So i tried 2048, and this results in too large of a primary key (https://github.com/pwncollege/dojo/commit/a5c8afb2edaf3952d737ca19864061be5c1dc89d).

We can now handle up to RSA-4096 with commit https://github.com/pwncollege/dojo/commit/be0de60fc37ed1906d45cb9598f53f61768f5c50.
`db.String(750)` is large enough to handle this, but small enough to not exceed the 3072-byte limit for primary keys.
I think the math here is `750 * 4 + 1 * 4 = 3004` (4-byte `user_id`), so technically we could go larger and not face this. It might also make sense to force ASCII for this field (possibly as simple as `db.String(750, charset="ascii")`), but I think since each character point is already <128, we should already be storage-efficient enough with `utf8mb4`.

This commit, which is pushed, also updates the ssh-key regex to complain louder about the requirements.

I think production still has the field as a `db.Text` and needs to be migrated to reflect this.

Thanks for the report!

**Comment by adamdoupe** [comment]
String should not be primary keys!!!

**Comment by spicydll** [comment]
> Strings should not be primary keys!!!

True. If public key length remains an issue or performance issues crop up, the proper way to do this is to add a column that contains a hash of the public key and use that along with the user id as the primary key instead.

**Comment by ConnorNelson** [comment]
So I understand as a general rule of thumb this is true.

In this case, `ssh_keys` is not, and almost certainly never will be referenced by another table, so we're not concerned about large foreign keys. We can cross that bridge if that ever changes (I can't imagine why it would).

SQLAlchemy requires that tables have a primary key in order to be mapped. We could trick SQLAlchemy if we really wanted to, but `(user_id, value)` does constitute a unique value, so I'm fine keeping it simple.

By specifying it as a primary key, it's indexed and guaranteed to be unique, which it should be; that's nice. We could create a synthetic primary key, and then specify that `(user_id, value)` is unique. The performance would be the same, and the storage/complexity will have marginally increased from the additional column. And for what? To be "textbook legit"?

Possibly if we want to optimize, we'd make the value's unique index be a `HASH` rather than a default `BTREE`, since we're more interested in fast exists/not-exists checks. But this is an optimization for O(1) vs O(log(n)) on a table that currently has < 10,000 rows on production. This query runs almost instantly, and rarely runs (how often is someone adding a new ssh key?). I don't think optimizing the speed of adding a new ssh key is seriously worth considering.


The DOJO has a number of much-needed optimization and software-engineering refactors/improvements. A string primary key for our `ssh_keys` table is not one of them.
